apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8shelloworld-deployment
  labels:
    app: k8shelloworld
spec:
  selector:
    matchLabels:
      app: k8shelloworld
  template:
    metadata:
      labels:
        app: k8shelloworld
    spec:
      containers:
      - name: k8shelloworld
        image: jordaan0/k8s_hello_world:version-0.0.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m