apiVersion: v1
kind: Service
metadata:
  name: k8shelloworld-service
spec:
  selector:
    app: k8shelloworld
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  externalIPs:
    - 10.0.1.1